In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import matplotlib.pyplot as plt

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
from sklearn.compose import ColumnTransformer

In [6]:
from sklearn.pipeline import Pipeline

In [7]:
from sklearn.preprocessing import RobustScaler, OneHotEncoder

In [8]:
from sklearn.linear_model import LogisticRegression

In [9]:
from sklearn.metrics import confusion_matrix, precision_score, accuracy_score, recall_score, f1_score

In [10]:
data=pd.read_csv("Churn_Modelling.csv",index_col=0)

In [11]:
data.head()

CustomerId   Surname  CreditScore Geography  Gender  Age  Tenure  \
RowNumber                                                                     
1            15634602  Hargrave          619    France  Female   42       2   
2            15647311      Hill          608     Spain  Female   41       1   
3            15619304      Onio          502    France  Female   42       8   
4            15701354      Boni          699    France  Female   39       1   
5            15737888  Mitchell          850     Spain  Female   43       2   

             Balance  NumOfProducts  HasCrCard  IsActiveMember  \
RowNumber                                                        
1               0.00              1          1               1   
2           83807.86              1          0               1   
3          159660.80              3          1               0   
4               0.00              2          0               0   
5          125510.82              1          1               1   

           EstimatedSalary  Exited  
RowNumber                           
1                101348.88       1  
2                112542.58       0  
3                113931.57       1  
4                 93826.63       0  
5                 79084.10       0

In [12]:
data.drop(columns=['CustomerId','Surname'])

CreditScore Geography  Gender  Age  Tenure    Balance  \
RowNumber                                                          
1                  619    France  Female   42       2       0.00   
2                  608     Spain  Female   41       1   83807.86   
3                  502    France  Female   42       8  159660.80   
4                  699    France  Female   39       1       0.00   
5                  850     Spain  Female   43       2  125510.82   
...                ...       ...     ...  ...     ...        ...   
9996               771    France    Male   39       5       0.00   
9997               516    France    Male   35      10   57369.61   
9998               709    France  Female   36       7       0.00   
9999               772   Germany    Male   42       3   75075.31   
10000              792    France  Female   28       4  130142.79   

           NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  Exited  
RowNumber                                                                     
1                      1          1               1        101348.88       1  
2                      1          0               1        112542.58       0  
3                      3          1               0        113931.57       1  
4                      2          0               0         93826.63       0  
5                      1          1               1         79084.10       0  
...                  ...        ...             ...              ...     ...  
9996                   2          1               0         96270.64       0  
9997                   1          1               1        101699.77       0  
9998                   1          0               1         42085.58       1  
9999                   2          1               0         92888.52       1  
10000                  1          1               0         38190.78       0  

[10000 rows x 11 columns]

In [13]:
print(data.shape)

(10000, 13)


In [14]:
print(data.isna().sum())

CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64


In [15]:
x=data.drop('Exited',axis=1)

In [16]:
y=data.Exited

In [17]:
print(y.value_counts())

Exited
0    7963
1    2037
Name: count, dtype: int64


In [18]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0,stratify=y)

In [19]:
print(x.columns)

Index(['CustomerId', 'Surname', 'CreditScore', 'Geography', 'Gender', 'Age',
       'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember',
       'EstimatedSalary'],
      dtype='object')


In [20]:
num_cols=['CreditScore','Age','Tenure','Balance','NumOfProducts','EstimatedSalary']

In [21]:
cat_cols=['Geography','Gender','HasCrCard','IsActiveMember']

In [22]:
p=Pipeline(steps=[('ct',ColumnTransformer(transformers=[('s1', RobustScaler(),num_cols), ('s2',OneHotEncoder(sparse_output=False, handle_unknown='ignore'),cat_cols)])),('mod',LogisticRegression(random_state=0))])

In [23]:
p.fit(x_train,y_train)


Pipeline(steps=[('ct',
                 ColumnTransformer(transformers=[('s1', RobustScaler(),
                                                  ['CreditScore', 'Age',
                                                   'Tenure', 'Balance',
                                                   'NumOfProducts',
                                                   'EstimatedSalary']),
                                                 ('s2',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['Geography', 'Gender',
                                                   'HasCrCard',
                                                   'IsActiveMember'])])),
                ('mod', LogisticRegression(random_state=0))])

In [24]:
preds=p.predict(x_test)

In [25]:
print(preds[:15])

[1 0 0 1 0 0 0 0 0 0 0 1 0 0 0]


In [26]:
print(confusion_matrix(y_true=y_test,y_pred=preds))

[[1530   63]
 [ 319   88]]


In [27]:
print(p.classes_)

[0 1]


In [28]:
print(confusion_matrix(y_test, preds, labels=(1,0)))
TP,FN,FP,TN=confusion_matrix(y_test, preds, labels=(1,0)).ravel()

[[  88  319]
 [  63 1530]]


In [29]:
print("Accuracy:" ,accuracy_score(y_test, preds))

Accuracy: 0.809


In [30]:
print("Precision:" ,precision_score(y_test,preds))

Precision: 0.5827814569536424


In [31]:
print("Recall : ",recall_score (y_test, preds))

Recall :  0.21621621621621623


In [32]:
print("F1-score:", f1_score(y_test, preds))

F1-score: 0.31541218637992835
